using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public enum FurnitureCategory { Seating, Table, Storage }

[Serializable]
public class PaintOption
{
    public string name;
    public string code;      // Dulux colour code, display only
    public Color color;
}

[Serializable]
public class MaterialOption
{
    public string name;
    public string sourceId;  // ambientCG asset id
    public Material material;
    public SurfaceKind targets;
}

[Serializable]
public class FurnitureOption
{
    public string name;
    public string sourceId;  // Poly Haven asset id
    public GameObject prefab;
    public FurnitureCategory category;
}

/// <summary>
/// The single bundled source the controller menu reads. Generated by
/// CatalogueImporter (Editor); never edited by hand.
/// </summary>
[CreateAssetMenu(menuName = "Renovation/Catalogue")]
public class Catalogue : ScriptableObject
{
    public List<PaintOption> paints = new();
    public List<MaterialOption> materials = new();
    public List<FurnitureOption> furniture = new();

    public IEnumerable<MaterialOption> MaterialsFor(SurfaceKind kind) =>
        materials.Where(m => m.material != null && (m.targets & kind) != 0);
}
