using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public enum FurnitureCategory { Seating, Table, Storage, Decor, Lighting, Bed }

[Serializable]
public class PaintOption
{
    public string name;
    public string code;      // Dulux colour code, display only
    public Color color;
}

[Serializable]
public class MaterialOption
{
    public string name;
    public string sourceId;  // ambientCG asset id
    public Material material;
    public SurfaceKind targets;
    public Color sampleColor = Color.white;   // average of the albedo; what a pulled sample starts from
}

[Serializable]
public class FurnitureOption
{
    public string name;
    public string sourceId;  // Poly Haven asset id
    public GameObject prefab;
    public FurnitureCategory category;
    public Texture2D thumbnail;   // rendered at import; shown on the menu chip
    public Color sampleColor = Color.white;   // average of the diffuse texture; what a pulled sample starts from
}

/// <summary>
/// The single bundled source the controller menu reads. Generated by
/// CatalogueImporter (Editor); never edited by hand.
/// </summary>
[CreateAssetMenu(menuName = "Renovation/Catalogue")]
public class Catalogue : ScriptableObject
{
    public List<PaintOption> paints = new();
    public List<MaterialOption> materials = new();
    public List<FurnitureOption> furniture = new();

    public FurnitureOption Furniture(string sourceId) => furniture.Find(f => f.sourceId == sourceId);
    public MaterialOption Material(string sourceId) => materials.Find(m => m.sourceId == sourceId);
    public PaintOption Paint(string name) => paints.Find(p => p.name == name);

    public IEnumerable<MaterialOption> MaterialsFor(SurfaceKind kind) =>
        materials.Where(m => m.material != null && (m.targets & kind) != 0);
}
