using System;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class SurfaceLookSpec
{
    public string surfaceName;
    public SurfaceState state = SurfaceState.Change;
    public Material material;          // catalogue material as the baseline, or null for the shipped one
    public Color color = Color.white;  // tint (a paint) — white for a textured base
    public bool userColour;            // true = counts as a chosen paint (keeps tinting a later material)
    public Color sampleColor = Color.white;
}

[Serializable]
public class PlacementSpec
{
    public string sourceId;            // catalogue furniture id
    public Vector3 position;
    public float yaw;
    public bool keep;                  // kept piece = sample source
    public Color sampleColor = Color.white;
}

/// <summary>
/// One pre-furnished starting room (Evaluation 1 §05: the task is rearranging, not
/// furnishing from empty). Same shell for every preset; only looks and furniture differ.
/// Generated by PresetAuthoring (Editor) from the catalogue; never edited by hand.
/// </summary>
[CreateAssetMenu(menuName = "Renovation/Room Preset")]
public class RoomPreset : ScriptableObject
{
    public string displayName;
    public Color floorSwatch = Color.white, wallSwatch = Color.white, accentSwatch = Color.white;
    public List<SurfaceLookSpec> looks = new();
    public List<PlacementSpec> furniture = new();
}
